#!/usr/bin/env bash
# Atlas Slurm installation and setup.
#
# ONE-TIME SETUP for the Slurm controller and compute daemons on Atlas.
# Atlas is a single-node cluster: the same host runs slurmctld (controller)
# and slurmd (compute). Student notebooks submit jobs via bind-mounted
# slurm.conf and munge socket.
#
# Read this script BEFORE running. It installs packages, creates users,
# and starts services as root. Run each section interactively the first time.
#
# Copyright (c) 2026 Andrew H. Bond. AGI-HPC Responsible AI License v1.0.

set -euo pipefail

# --------------------------------------------------------------------------
# Colors for humans
# --------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${YELLOW}▶ $*${NC}"; }
ok()    { echo -e "${GREEN}✓ $*${NC}"; }
die()   { echo -e "${RED}✗ $*${NC}"; exit 1; }

# --------------------------------------------------------------------------
# Sanity checks
# --------------------------------------------------------------------------
[[ $EUID -eq 0 ]] || die "Must be run as root (use sudo)."
command -v apt-get >/dev/null || die "This script assumes apt-based Ubuntu/Debian."

ATLAS_HOSTNAME="$(hostname -s)"
[[ "$ATLAS_HOSTNAME" == "atlas" ]] || {
    info "Hostname is '$ATLAS_HOSTNAME', not 'atlas'. Adjusting slurm.conf template."
}

# --------------------------------------------------------------------------
# 1. Install packages
# --------------------------------------------------------------------------
info "Installing munge + slurm-wlm..."
apt-get update
apt-get install -y --no-install-recommends \
    munge \
    slurm-wlm \
    slurm-client \
    slurmctld \
    slurmd
ok "Packages installed."

# --------------------------------------------------------------------------
# 2. Munge key + permissions
# --------------------------------------------------------------------------
info "Configuring munge..."
if [[ ! -f /etc/munge/munge.key ]]; then
    /usr/sbin/create-munge-key -r
    ok "Munge key generated."
else
    ok "Munge key already exists."
fi
chown munge:munge /etc/munge/munge.key
chmod 400 /etc/munge/munge.key
chown -R munge:munge /var/log/munge /var/lib/munge /etc/munge /run/munge 2>/dev/null || true

systemctl enable munge
systemctl restart munge
sleep 1
munge -n | unmunge > /dev/null 2>&1 && ok "Munge self-test passed." || die "Munge self-test failed."

# --------------------------------------------------------------------------
# 3. Slurm users and directories
# --------------------------------------------------------------------------
info "Setting up slurm user and directories..."
id -u slurm >/dev/null 2>&1 || useradd -r -s /usr/sbin/nologin -d /var/lib/slurm slurm

mkdir -p /var/spool/slurmd /var/spool/slurmctld /var/log/slurm /etc/slurm
chown slurm:slurm /var/spool/slurmd /var/spool/slurmctld /var/log/slurm
chmod 755 /var/spool/slurmd /var/spool/slurmctld
ok "Directories created."

# --------------------------------------------------------------------------
# 4. Slurm configuration
# --------------------------------------------------------------------------
info "Writing /etc/slurm/slurm.conf..."

# Detect CPU and memory for the node configuration
CPUS=$(nproc)
REAL_MEM_MB=$(( $(awk '/MemTotal/ {print $2}' /proc/meminfo) / 1024 ))
# Reserve ~16 GB for host overhead (agi-hpc services, postgres, etc.)
NODE_MEM_MB=$(( REAL_MEM_MB - 16384 ))
[[ $NODE_MEM_MB -lt 32768 ]] && NODE_MEM_MB=32768

cat > /etc/slurm/slurm.conf <<EOF
# Atlas single-node Slurm configuration
# Generated by install-slurm-atlas.sh on $(date -Iseconds)

# -------------------------
# Cluster
# -------------------------
ClusterName=atlas
SlurmctldHost=${ATLAS_HOSTNAME}
AuthType=auth/munge
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SwitchType=switch/none
MpiDefault=none
ProctrackType=proctrack/cgroup
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmUser=slurm
SlurmdUser=root
SlurmctldPort=6817
SlurmdPort=6818
ReturnToService=2

# -------------------------
# Scheduling
# -------------------------
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory

# -------------------------
# Accounting
# -------------------------
AccountingStorageType=accounting_storage/filetxt
AccountingStorageLoc=/var/log/slurm/accounting
JobAcctGatherType=jobacct_gather/cgroup

# -------------------------
# Logging
# -------------------------
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log

# -------------------------
# Node definition
# Atlas acts as both controller and compute node.
# GRES: 2x GV100 GPUs (update if hardware changes).
# -------------------------
GresTypes=gpu
NodeName=${ATLAS_HOSTNAME} CPUs=${CPUS} RealMemory=${NODE_MEM_MB} Gres=gpu:gv100:2 State=UNKNOWN

# -------------------------
# Partitions
# -------------------------
# interactive: fast-turnaround cells from Jupyter notebooks
PartitionName=interactive Nodes=${ATLAS_HOSTNAME} \
    MaxTime=00:30:00 MaxCPUsPerNode=2 MaxMemPerNode=8192 \
    DefaultTime=00:10:00 State=UP Priority=100

# cpu: general CPU compute
PartitionName=cpu Nodes=${ATLAS_HOSTNAME} \
    MaxTime=04:00:00 MaxCPUsPerNode=8 MaxMemPerNode=32768 \
    DefaultTime=00:30:00 State=UP Priority=50

# gpu: student GPU access (opt-in via gpu_users.txt)
PartitionName=gpu Nodes=${ATLAS_HOSTNAME} \
    MaxTime=04:00:00 MaxCPUsPerNode=8 MaxMemPerNode=65536 \
    DefaultTime=00:30:00 State=UP Priority=50 \
    AllowAccounts=gpu_users

# research: Andrew's partition, preempts everything else
PartitionName=research Nodes=${ATLAS_HOSTNAME} \
    MaxTime=UNLIMITED Default=YES State=UP Priority=1000 \
    AllowAccounts=research \
    PreemptMode=requeue
EOF
chmod 644 /etc/slurm/slurm.conf
ok "slurm.conf written."

info "Writing /etc/slurm/cgroup.conf..."
cat > /etc/slurm/cgroup.conf <<'EOF'
CgroupAutomount=yes
ConstrainCores=yes
ConstrainDevices=yes
ConstrainRAMSpace=yes
ConstrainSwapSpace=yes
EOF
chmod 644 /etc/slurm/cgroup.conf
ok "cgroup.conf written."

info "Writing /etc/slurm/gres.conf..."
cat > /etc/slurm/gres.conf <<'EOF'
# 2x NVIDIA GV100 GPUs. Update if hardware changes.
NodeName=DEFAULT Name=gpu Type=gv100 File=/dev/nvidia0
NodeName=DEFAULT Name=gpu Type=gv100 File=/dev/nvidia1
EOF
chmod 644 /etc/slurm/gres.conf
ok "gres.conf written."

# --------------------------------------------------------------------------
# 5. Start services
# --------------------------------------------------------------------------
info "Enabling and starting Slurm services..."
systemctl enable slurmctld
systemctl enable slurmd
systemctl restart slurmctld
sleep 2
systemctl restart slurmd
sleep 2
ok "Services started."

info "Verifying..."
if sinfo > /dev/null 2>&1; then
    sinfo
    ok "sinfo returns state. Slurm is up."
else
    die "sinfo failed. Check: journalctl -u slurmctld -u slurmd"
fi

# --------------------------------------------------------------------------
# 6. Create Slurm accounts
# --------------------------------------------------------------------------
info "Creating Slurm accounts..."
# Uses filetxt accounting — accounts are created by sacctmgr if sacct
# backend is running. For filetxt, accounts are implicit; we only need
# the AllowAccounts directives in slurm.conf to gate partition access.
#
# Users submit under their Linux UID; accountability is by username.
# The 'gpu_users' and 'research' accounts are conceptual here — real
# gating happens via the filesystem permissions on /etc/slurm and the
# Linux group membership of the submitting user.
ok "Slurm accounting is filetxt-based; no sacctmgr setup needed."

# --------------------------------------------------------------------------
# 7. Create the jhub group (shared group for all students)
# --------------------------------------------------------------------------
info "Creating jhub group..."
getent group jhub >/dev/null || groupadd jhub
ok "jhub group exists (GID: $(getent group jhub | cut -d: -f3))."

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------
cat <<EOF

$(echo -e "${GREEN}=========================================${NC}")
$(echo -e "${GREEN}  Atlas Slurm installation complete       ${NC}")
$(echo -e "${GREEN}=========================================${NC}")

Node: ${ATLAS_HOSTNAME}
CPUs: ${CPUS}
Memory: ${NODE_MEM_MB} MB available to Slurm
GPUs:  2 (GV100) — see gres.conf
Partitions: interactive, cpu, gpu, research

Next steps:
  1. Test from root:     sinfo && squeue
  2. Test a simple job:  su -c 'srun hostname' slurm
  3. Sync student accounts: sudo ./sync-student-accounts.sh
  4. Bring up JupyterHub:   cd .. && docker compose up -d

To reconfigure:
  - Edit /etc/slurm/slurm.conf
  - sudo scontrol reconfigure

To restart on failure:
  - sudo systemctl restart munge slurmctld slurmd
EOF
